### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by gabru-md** [nsITians/sho.rt#3]
Please do the following changes regarding 
`How to use?` part

Remove the single statements for dependencies and add
`npm install` 
instead of it.

Thanks!

**Comment by lex111** [comment]
Assign to me please.

**Comment by skyth3r** [comment]
If this is needs to be worked on I don't mind lending a hand

**Comment by anshumanv** [comment]
Working on it

**Comment by arihant-001** [comment]
@gabru-md can u explain in more detail
